- id: doi:10.1124/jpet.123.001773
  description: A study on the effects of aminopyridines, particularly 3,4-diaminopyridine (3,4-DAP), on ventilation and respiration in botulism reveals significant improvements in respiratory function and acid-base balance, suggesting potential as a therapeutic option and laying groundwork for further development of aminopyridine derivatives.
  image: https://pubmed.ncbi.nlm.nih.gov/37977816/#&gid=article-figures&pid=fig-1-uid-0.png
  
  - id: pubmed:29424689
